version: '2'
services:
  tester:
    build: .
    image: summon-aws-secrets-tester
    ports:
      - "8080"
    entrypoint: /bin/bash
    command: './test-entrypoint.sh'
    volumes:
      - .:/go/src/github.com/cyberark/summon-aws-secrets

